from __future__ import annotations

from dataclasses import asdict

from .styles import StyleOptions, style_from_option_mapping


_PRESET_DIFFS: dict[str, dict[str, object]] = {
    "Academic": {
        "body_font": "Times New Roman",
        "line_height": 1.8,
        "heading_font": "Georgia",
        "heading_color": "#1a1a2e",
        "heading_h1_color": "#1a1a2e",
        "heading_h2_color": "#2d3748",
        "heading_h3_color": "#4a5568",
        "heading_h1_size_px": 24,
        "heading_h2_size_px": 20,
        "heading_h3_size_px": 16,
        "heading_h4_size_px": 14,
        "heading_h5_size_px": 13,
        "code_font": "Courier New",
        "code_font_size": 10,
        "code_line_height": 1.4,
        "code_theme": "friendly",
        "margin_top_mm": 30.0,
        "margin_right_mm": 30.0,
        "margin_bottom_mm": 30.0,
        "margin_left_mm": 30.0,
        "footer_align": "center",
        "image_scale": 0.8,
    },
    "Magazine": {
        "body_font": "Georgia",
        "body_font_size": 11,
        "line_height": 1.6,
        "heading_font": "Arial",
        "heading_color": "#b91c1c",
        "heading_h1_color": "#b91c1c",
        "heading_h2_color": "#991b1b",
        "heading_h3_color": "#4a5568",
        "heading_h4_color": "#6b7280",
        "heading_h1_size_px": 36,
        "heading_h2_size_px": 24,
        "heading_h3_size_px": 16,
        "heading_h4_size_px": 14,
        "heading_h5_size_px": 12,
        "heading_h6_size_px": 11,
        "code_font_size": 10,
        "code_line_height": 1.35,
        "code_theme": "friendly",
        "margin_top_mm": 20.0,
        "margin_right_mm": 22.0,
        "margin_bottom_mm": 20.0,
        "margin_left_mm": 22.0,
        "footer_align": "center",
        "footer_color": "#b91c1c",
        "footnote_font_size": 8.5,
        "footnote_text_color": "#6b7280",
        "footnote_marker_color": "#b91c1c",
        "table_row_stripes": True,
        "table_row_even_color": "#fef2f2",
        "table_cell_padding_y_px": 8,
        "table_cell_padding_x_px": 12,
        "image_scale": 0.95,
    },
    "Corporate": {
        "body_font": "Calibri",
        "body_font_size": 11,
        "heading_font": "Calibri",
        "heading_color": "#1e3a5f",
        "heading_h1_color": "#1e3a5f",
        "heading_h2_color": "#2563eb",
        "heading_h3_color": "#475569",
        "heading_h4_color": "#64748b",
        "heading_h1_size_px": 26,
        "heading_h2_size_px": 20,
        "heading_h3_size_px": 16,
        "heading_h4_size_px": 14,
        "heading_h5_size_px": 12,
        "heading_h6_size_px": 11,
        "code_font_size": 10,
        "code_line_height": 1.4,
        "margin_top_mm": 25.0,
        "margin_right_mm": 25.0,
        "margin_bottom_mm": 25.0,
        "margin_left_mm": 25.0,
        "footer_color": "#94a3b8",
        "footnote_font_size": 8.5,
        "footnote_text_color": "#64748b",
        "footnote_marker_color": "#2563eb",
        "table_row_stripes": True,
        "table_row_even_color": "#f1f5f9",
        "table_cell_padding_x_px": 10,
        "image_scale": 0.85,
        "show_horizontal_rules": False,
    },
    "Technical": {
        "body_font_size": 10,
        "line_height": 1.4,
        "heading_font": "Consolas",
        "heading_color": "#0f172a",
        "heading_h1_color": "#059669",
        "heading_h2_color": "#047857",
        "heading_h3_color": "#334155",
        "heading_h4_color": "#475569",
        "heading_h1_size_px": 22,
        "heading_h2_size_px": 18,
        "heading_h3_size_px": 14,
        "heading_h4_size_px": 12,
        "heading_h5_size_px": 11,
        "heading_h6_size_px": 10,
        "code_font_size": 10,
        "code_line_height": 1.25,
        "code_theme": "monokai",
        "margin_top_mm": 18.0,
        "margin_right_mm": 18.0,
        "margin_bottom_mm": 18.0,
        "margin_left_mm": 18.0,
        "footnote_font_size": 8.0,
        "footnote_text_color": "#6b7280",
        "footnote_marker_color": "#059669",
        "table_row_stripes": True,
        "table_row_even_color": "#ecfdf5",
        "table_cell_padding_y_px": 3,
        "table_cell_padding_x_px": 5,
        "image_scale": 0.75,
        "show_horizontal_rules": False,
    },
    "Minimal": {
        "body_font": "Arial",
        "body_font_size": 10,
        "line_height": 1.3,
        "heading_font": "Arial",
        "heading_color": "#000000",
        "heading_h1_color": "#000000",
        "heading_h2_color": "#000000",
        "heading_h3_color": "#333333",
        "heading_h4_color": "#333333",
        "heading_h1_size_px": 20,
        "heading_h2_size_px": 16,
        "heading_h3_size_px": 13,
        "heading_h4_size_px": 11,
        "heading_h5_size_px": 10,
        "heading_h6_size_px": 10,
        "code_font": "Courier New",
        "code_font_size": 9,
        "code_line_height": 1.2,
        "margin_top_mm": 12.0,
        "margin_right_mm": 12.0,
        "margin_bottom_mm": 12.0,
        "margin_left_mm": 12.0,
        "footer_color": "#999999",
        "include_footnotes": False,
        "footnote_font_size": 7.5,
        "footnote_text_color": "#666666",
        "footnote_marker_color": "#333333",
        "table_row_even_color": "#f5f5f5",
        "table_cell_padding_y_px": 2,
        "table_cell_padding_x_px": 4,
        "image_scale": 0.65,
        "show_horizontal_rules": False,
    },
    "Notebook": {
        "body_font": "Georgia",
        "line_height": 1.7,
        "heading_color": "#78350f",
        "heading_h1_color": "#78350f",
        "heading_h2_color": "#92400e",
        "heading_h3_color": "#a16207",
        "heading_h4_color": "#b45309",
        "heading_h2_size_px": 20,
        "heading_h3_size_px": 17,
        "heading_h4_size_px": 15,
        "heading_h5_size_px": 13,
        "code_font": "Courier New",
        "code_line_height": 1.5,
        "code_theme": "xcode",
        "margin_top_mm": 28.0,
        "margin_right_mm": 28.0,
        "margin_bottom_mm": 28.0,
        "margin_left_mm": 28.0,
        "footer_align": "center",
        "footer_color": "#a16207",
        "footnote_text_color": "#78350f",
        "footnote_marker_color": "#92400e",
        "table_row_stripes": True,
        "table_row_odd_color": "#fffbeb",
        "table_row_even_color": "#fef3c7",
        "table_cell_padding_y_px": 7,
        "table_cell_padding_x_px": 10,
        "image_scale": 0.85,
    },
    "Creative": {
        "body_font_size": 11,
        "line_height": 1.55,
        "heading_font": "Georgia",
        "heading_color": "#581c87",
        "heading_h1_color": "#7c3aed",
        "heading_h2_color": "#6d28d9",
        "heading_h3_color": "#581c87",
        "heading_h4_color": "#6b7280",
        "heading_h1_size_px": 32,
        "heading_h3_size_px": 16,
        "heading_h4_size_px": 14,
        "heading_h5_size_px": 12,
        "heading_h6_size_px": 11,
        "code_font_size": 10,
        "code_line_height": 1.4,
        "code_theme": "dracula",
        "margin_top_mm": 22.0,
        "margin_right_mm": 20.0,
        "margin_bottom_mm": 22.0,
        "margin_left_mm": 35.0,
        "footer_color": "#7c3aed",
        "footnote_font_size": 8.5,
        "footnote_text_color": "#6b7280",
        "footnote_marker_color": "#7c3aed",
        "table_row_stripes": True,
        "table_row_even_color": "#f5f3ff",
        "table_cell_padding_x_px": 10,
    },
    "Developer": {
        "body_font_size": 11,
        "heading_font": "Consolas",
        "heading_color": "#0f172a",
        "heading_h1_color": "#0ea5e9",
        "heading_h2_color": "#0284c7",
        "heading_h3_color": "#334155",
        "heading_h4_color": "#475569",
        "heading_h1_size_px": 26,
        "heading_h2_size_px": 20,
        "heading_h3_size_px": 16,
        "heading_h4_size_px": 13,
        "heading_h5_size_px": 12,
        "heading_h6_size_px": 11,
        "code_line_height": 1.35,
        "code_theme": "native",
        "margin_top_mm": 20.0,
        "margin_right_mm": 20.0,
        "margin_bottom_mm": 20.0,
        "margin_left_mm": 20.0,
        "footer_color": "#475569",
        "footnote_font_size": 8.5,
        "footnote_text_color": "#64748b",
        "footnote_marker_color": "#0ea5e9",
        "table_row_stripes": True,
        "table_row_even_color": "#f0f9ff",
        "table_cell_padding_y_px": 5,
        "image_scale": 0.8,
        "show_horizontal_rules": False,
    },
    "Elegant": {
        "body_font": "Georgia",
        "line_height": 1.7,
        "heading_font": "Times New Roman",
        "heading_color": "#18181b",
        "heading_h1_color": "#18181b",
        "heading_h2_color": "#27272a",
        "heading_h3_color": "#3f3f46",
        "heading_h4_color": "#52525b",
        "heading_h1_size_px": 30,
        "heading_h2_size_px": 22,
        "heading_h3_size_px": 17,
        "heading_h4_size_px": 14,
        "heading_h5_size_px": 13,
        "code_font": "Courier New",
        "code_font_size": 10,
        "code_line_height": 1.4,
        "code_theme": "vim",
        "margin_top_mm": 35.0,
        "margin_right_mm": 30.0,
        "margin_bottom_mm": 35.0,
        "margin_left_mm": 30.0,
        "footer_align": "center",
        "footer_color": "#a1a1aa",
        "footnote_text_color": "#52525b",
        "footnote_marker_color": "#18181b",
        "table_row_even_color": "#fafafa",
        "table_cell_padding_y_px": 8,
        "table_cell_padding_x_px": 14,
        "image_scale": 0.85,
    },
}

BUILTIN_PRESET_STYLES: dict[str, StyleOptions] = {
    name: style_from_option_mapping(values) for name, values in _PRESET_DIFFS.items()
}
BUILTIN_PRESET_NAMES: list[str] = sorted(BUILTIN_PRESET_STYLES)


def _clean_preset_name(name: str) -> str:
    return name.removesuffix(" (built-in)").strip()


def is_builtin_preset(name: str) -> bool:
    return _clean_preset_name(name) in BUILTIN_PRESET_STYLES


def get_builtin_preset(name: str) -> StyleOptions | None:
    preset = BUILTIN_PRESET_STYLES.get(_clean_preset_name(name))
    if preset is None:
        return None
    return StyleOptions(**asdict(preset))
