"""Built-in style presets shipped with the application.

Each preset is a partial state dict compatible with ``StateManager.apply_state``.
Only style-relevant keys are included — file paths and UI preferences are left
untouched when a built-in preset is loaded.
"""

from __future__ import annotations

BUILTIN_PRESETS: dict[str, dict[str, object]] = {
    "Academic": {
        "body_font_var": "Times New Roman",
        "heading_font_var": "Georgia",
        "body_size_var": 12,
        "line_height_var": 1.6,
        "heading_color_var": "#1a1a2e",
        "heading_h1_color_var": "#1a1a2e",
        "heading_h2_color_var": "#2d3748",
        "heading_h3_color_var": "#4a5568",
        "heading_h4_color_var": "",
        "heading_h5_color_var": "",
        "heading_h6_color_var": "",
        "heading_h1_size_var": 26,
        "heading_h2_size_var": 21,
        "heading_h3_size_var": 17,
        "heading_h4_size_var": 15,
        "heading_h5_size_var": 13,
        "heading_h6_size_var": 12,
        "code_font_var": "Courier New",
        "code_size_var": 10,
        "code_line_height_var": 1.4,
        "code_theme_var": "friendly",
        "margin_top_var": 30.0,
        "margin_right_var": 25.4,
        "margin_bottom_var": 30.0,
        "margin_left_var": 25.4,
        "footer_text_var": "",
        "footer_align_var": "Center",
        "include_notes_var": True,
        "footnote_size_var": 9.0,
        "footnote_text_color_var": "#374151",
        "footnote_marker_color_var": "#111827",
        "table_stripes_var": False,
        "table_odd_color_var": "#ffffff",
        "table_even_color_var": "#f3f4f6",
        "table_pad_y_var": 6,
        "table_pad_x_var": 8,
        "image_scale_var": 85.0,
        "show_horizontal_rules_var": True,
    },
    "Modern": {
        "body_font_var": "Segoe UI",
        "heading_font_var": "Segoe UI",
        "body_size_var": 12,
        "line_height_var": 1.5,
        "heading_color_var": "#0f172a",
        "heading_h1_color_var": "#1e40af",
        "heading_h2_color_var": "#1e3a8a",
        "heading_h3_color_var": "#1e293b",
        "heading_h4_color_var": "",
        "heading_h5_color_var": "",
        "heading_h6_color_var": "",
        "heading_h1_size_var": 28,
        "heading_h2_size_var": 22,
        "heading_h3_size_var": 18,
        "heading_h4_size_var": 16,
        "heading_h5_size_var": 14,
        "heading_h6_size_var": 12,
        "code_font_var": "Consolas",
        "code_size_var": 11,
        "code_line_height_var": 1.45,
        "code_theme_var": "default",
        "margin_top_var": 25.4,
        "margin_right_var": 25.4,
        "margin_bottom_var": 25.4,
        "margin_left_var": 25.4,
        "footer_text_var": "",
        "footer_align_var": "Right",
        "include_notes_var": True,
        "footnote_size_var": 9.0,
        "footnote_text_color_var": "#374151",
        "footnote_marker_color_var": "#111827",
        "table_stripes_var": True,
        "table_odd_color_var": "#ffffff",
        "table_even_color_var": "#f0f4ff",
        "table_pad_y_var": 6,
        "table_pad_x_var": 10,
        "image_scale_var": 90.0,
        "show_horizontal_rules_var": True,
    },
    "Technical": {
        "body_font_var": "Calibri",
        "heading_font_var": "Calibri",
        "body_size_var": 11,
        "line_height_var": 1.45,
        "heading_color_var": "#1f2937",
        "heading_h1_color_var": "#065f46",
        "heading_h2_color_var": "#064e3b",
        "heading_h3_color_var": "#1f2937",
        "heading_h4_color_var": "",
        "heading_h5_color_var": "",
        "heading_h6_color_var": "",
        "heading_h1_size_var": 26,
        "heading_h2_size_var": 20,
        "heading_h3_size_var": 16,
        "heading_h4_size_var": 14,
        "heading_h5_size_var": 13,
        "heading_h6_size_var": 12,
        "code_font_var": "Consolas",
        "code_size_var": 10,
        "code_line_height_var": 1.3,
        "code_theme_var": "monokai",
        "margin_top_var": 20.0,
        "margin_right_var": 20.0,
        "margin_bottom_var": 20.0,
        "margin_left_var": 20.0,
        "footer_text_var": "",
        "footer_align_var": "Right",
        "include_notes_var": True,
        "footnote_size_var": 8.5,
        "footnote_text_color_var": "#374151",
        "footnote_marker_color_var": "#111827",
        "table_stripes_var": True,
        "table_odd_color_var": "#ffffff",
        "table_even_color_var": "#ecfdf5",
        "table_pad_y_var": 4,
        "table_pad_x_var": 6,
        "image_scale_var": 90.0,
        "show_horizontal_rules_var": False,
    },
    "Minimal": {
        "body_font_var": "Arial",
        "heading_font_var": "Arial",
        "body_size_var": 11,
        "line_height_var": 1.4,
        "heading_color_var": "#000000",
        "heading_h1_color_var": "",
        "heading_h2_color_var": "",
        "heading_h3_color_var": "",
        "heading_h4_color_var": "",
        "heading_h5_color_var": "",
        "heading_h6_color_var": "",
        "heading_h1_size_var": 24,
        "heading_h2_size_var": 19,
        "heading_h3_size_var": 16,
        "heading_h4_size_var": 14,
        "heading_h5_size_var": 12,
        "heading_h6_size_var": 11,
        "code_font_var": "Courier New",
        "code_size_var": 10,
        "code_line_height_var": 1.35,
        "code_theme_var": "default",
        "margin_top_var": 15.0,
        "margin_right_var": 15.0,
        "margin_bottom_var": 15.0,
        "margin_left_var": 15.0,
        "footer_text_var": "",
        "footer_align_var": "Right",
        "include_notes_var": False,
        "footnote_size_var": 8.0,
        "footnote_text_color_var": "#374151",
        "footnote_marker_color_var": "#111827",
        "table_stripes_var": False,
        "table_odd_color_var": "#ffffff",
        "table_even_color_var": "#f3f4f6",
        "table_pad_y_var": 4,
        "table_pad_x_var": 5,
        "image_scale_var": 80.0,
        "show_horizontal_rules_var": False,
    },
    "Dark Code": {
        "body_font_var": "Segoe UI",
        "heading_font_var": "Segoe UI",
        "body_size_var": 12,
        "line_height_var": 1.5,
        "heading_color_var": "#1e293b",
        "heading_h1_color_var": "#1e40af",
        "heading_h2_color_var": "#2563eb",
        "heading_h3_color_var": "#334155",
        "heading_h4_color_var": "",
        "heading_h5_color_var": "",
        "heading_h6_color_var": "",
        "heading_h1_size_var": 28,
        "heading_h2_size_var": 22,
        "heading_h3_size_var": 18,
        "heading_h4_size_var": 16,
        "heading_h5_size_var": 14,
        "heading_h6_size_var": 12,
        "code_font_var": "Consolas",
        "code_size_var": 11,
        "code_line_height_var": 1.45,
        "code_theme_var": "dracula",
        "margin_top_var": 25.4,
        "margin_right_var": 25.4,
        "margin_bottom_var": 25.4,
        "margin_left_var": 25.4,
        "footer_text_var": "",
        "footer_align_var": "Right",
        "include_notes_var": True,
        "footnote_size_var": 9.0,
        "footnote_text_color_var": "#64748b",
        "footnote_marker_color_var": "#2563eb",
        "table_stripes_var": True,
        "table_odd_color_var": "#ffffff",
        "table_even_color_var": "#f1f5f9",
        "table_pad_y_var": 6,
        "table_pad_x_var": 8,
        "image_scale_var": 90.0,
        "show_horizontal_rules_var": True,
    },
}

BUILTIN_PRESET_NAMES: list[str] = sorted(BUILTIN_PRESETS.keys())

# Keys that are style-only (presets should not overwrite file paths or UI prefs)
_NON_STYLE_KEYS = frozenset({
    "markdown_var",
    "output_dir_var",
    "format_var",
    "ui_theme_var",
    "auto_preview_var",
})


def is_builtin_preset(name: str) -> bool:
    """Return True if *name* (without suffix) matches a built-in preset."""
    clean = name.removesuffix(" (built-in)").strip()
    return clean in BUILTIN_PRESETS


def get_builtin_preset(name: str) -> dict[str, object] | None:
    """Return a copy of the built-in preset dict, or None."""
    clean = name.removesuffix(" (built-in)").strip()
    preset = BUILTIN_PRESETS.get(clean)
    if preset is None:
        return None
    return dict(preset)
