"""Built-in style presets shipped with the application.

Each preset is a partial state dict compatible with ``StateManager.apply_state``.
Only style-relevant keys are included — file paths and UI preferences are left
untouched when a built-in preset is loaded.
"""

from __future__ import annotations

BUILTIN_PRESETS: dict[str, dict[str, object]] = {
    # ── Formal serif style for academic papers, theses, reports ──────────
    "Academic": {
        "body_font_var": "Times New Roman",
        "heading_font_var": "Georgia",
        "body_size_var": 12,
        "line_height_var": 1.8,
        "heading_color_var": "#1a1a2e",
        "heading_h1_color_var": "#1a1a2e",
        "heading_h2_color_var": "#2d3748",
        "heading_h3_color_var": "#4a5568",
        "heading_h4_color_var": "",
        "heading_h5_color_var": "",
        "heading_h6_color_var": "",
        "heading_h1_size_var": 24,
        "heading_h2_size_var": 20,
        "heading_h3_size_var": 16,
        "heading_h4_size_var": 14,
        "heading_h5_size_var": 13,
        "heading_h6_size_var": 12,
        "code_font_var": "Courier New",
        "code_size_var": 10,
        "code_line_height_var": 1.4,
        "code_theme_var": "friendly",
        "margin_top_var": 30.0,
        "margin_right_var": 30.0,
        "margin_bottom_var": 30.0,
        "margin_left_var": 30.0,
        "footer_text_var": "",
        "footer_color_var": "#6b7280",
        "footer_align_var": "Center",
        "include_notes_var": True,
        "footnote_size_var": 9.0,
        "footnote_text_color_var": "#374151",
        "footnote_marker_color_var": "#111827",
        "table_stripes_var": False,
        "table_odd_color_var": "#ffffff",
        "table_even_color_var": "#f3f4f6",
        "table_pad_y_var": 6,
        "table_pad_x_var": 8,
        "image_scale_var": 80.0,
        "show_horizontal_rules_var": True,
    },
    # ── Bold and colorful, magazine-like editorial layout ─────────────────
    "Magazine": {
        "body_font_var": "Georgia",
        "heading_font_var": "Arial",
        "body_size_var": 11,
        "line_height_var": 1.6,
        "heading_color_var": "#b91c1c",
        "heading_h1_color_var": "#b91c1c",
        "heading_h2_color_var": "#991b1b",
        "heading_h3_color_var": "#4a5568",
        "heading_h4_color_var": "#6b7280",
        "heading_h5_color_var": "",
        "heading_h6_color_var": "",
        "heading_h1_size_var": 36,
        "heading_h2_size_var": 24,
        "heading_h3_size_var": 16,
        "heading_h4_size_var": 14,
        "heading_h5_size_var": 12,
        "heading_h6_size_var": 11,
        "code_font_var": "Consolas",
        "code_size_var": 10,
        "code_line_height_var": 1.35,
        "code_theme_var": "friendly",
        "margin_top_var": 20.0,
        "margin_right_var": 22.0,
        "margin_bottom_var": 20.0,
        "margin_left_var": 22.0,
        "footer_text_var": "",
        "footer_color_var": "#b91c1c",
        "footer_align_var": "Center",
        "include_notes_var": True,
        "footnote_size_var": 8.5,
        "footnote_text_color_var": "#6b7280",
        "footnote_marker_color_var": "#b91c1c",
        "table_stripes_var": True,
        "table_odd_color_var": "#ffffff",
        "table_even_color_var": "#fef2f2",
        "table_pad_y_var": 8,
        "table_pad_x_var": 12,
        "image_scale_var": 95.0,
        "show_horizontal_rules_var": True,
    },
    # ── Clean corporate look, blue-gray palette ──────────────────────────
    "Corporate": {
        "body_font_var": "Calibri",
        "heading_font_var": "Calibri",
        "body_size_var": 11,
        "line_height_var": 1.5,
        "heading_color_var": "#1e3a5f",
        "heading_h1_color_var": "#1e3a5f",
        "heading_h2_color_var": "#2563eb",
        "heading_h3_color_var": "#475569",
        "heading_h4_color_var": "#64748b",
        "heading_h5_color_var": "",
        "heading_h6_color_var": "",
        "heading_h1_size_var": 26,
        "heading_h2_size_var": 20,
        "heading_h3_size_var": 16,
        "heading_h4_size_var": 14,
        "heading_h5_size_var": 12,
        "heading_h6_size_var": 11,
        "code_font_var": "Consolas",
        "code_size_var": 10,
        "code_line_height_var": 1.4,
        "code_theme_var": "default",
        "margin_top_var": 25.0,
        "margin_right_var": 25.0,
        "margin_bottom_var": 25.0,
        "margin_left_var": 25.0,
        "footer_text_var": "",
        "footer_color_var": "#94a3b8",
        "footer_align_var": "Right",
        "include_notes_var": True,
        "footnote_size_var": 8.5,
        "footnote_text_color_var": "#64748b",
        "footnote_marker_color_var": "#2563eb",
        "table_stripes_var": True,
        "table_odd_color_var": "#ffffff",
        "table_even_color_var": "#f1f5f9",
        "table_pad_y_var": 6,
        "table_pad_x_var": 10,
        "image_scale_var": 85.0,
        "show_horizontal_rules_var": False,
    },
    # ── Dense technical doc, code-first, tight spacing ───────────────────
    "Technical": {
        "body_font_var": "Segoe UI",
        "heading_font_var": "Consolas",
        "body_size_var": 10,
        "line_height_var": 1.4,
        "heading_color_var": "#0f172a",
        "heading_h1_color_var": "#059669",
        "heading_h2_color_var": "#047857",
        "heading_h3_color_var": "#334155",
        "heading_h4_color_var": "#475569",
        "heading_h5_color_var": "",
        "heading_h6_color_var": "",
        "heading_h1_size_var": 22,
        "heading_h2_size_var": 18,
        "heading_h3_size_var": 14,
        "heading_h4_size_var": 12,
        "heading_h5_size_var": 11,
        "heading_h6_size_var": 10,
        "code_font_var": "Consolas",
        "code_size_var": 10,
        "code_line_height_var": 1.25,
        "code_theme_var": "monokai",
        "margin_top_var": 18.0,
        "margin_right_var": 18.0,
        "margin_bottom_var": 18.0,
        "margin_left_var": 18.0,
        "footer_text_var": "",
        "footer_color_var": "#6b7280",
        "footer_align_var": "Right",
        "include_notes_var": True,
        "footnote_size_var": 8.0,
        "footnote_text_color_var": "#6b7280",
        "footnote_marker_color_var": "#059669",
        "table_stripes_var": True,
        "table_odd_color_var": "#ffffff",
        "table_even_color_var": "#ecfdf5",
        "table_pad_y_var": 3,
        "table_pad_x_var": 5,
        "image_scale_var": 75.0,
        "show_horizontal_rules_var": False,
    },
    # ── Absolute bare minimum, max content density ───────────────────────
    "Minimal": {
        "body_font_var": "Arial",
        "heading_font_var": "Arial",
        "body_size_var": 10,
        "line_height_var": 1.3,
        "heading_color_var": "#000000",
        "heading_h1_color_var": "#000000",
        "heading_h2_color_var": "#000000",
        "heading_h3_color_var": "#333333",
        "heading_h4_color_var": "#333333",
        "heading_h5_color_var": "",
        "heading_h6_color_var": "",
        "heading_h1_size_var": 20,
        "heading_h2_size_var": 16,
        "heading_h3_size_var": 13,
        "heading_h4_size_var": 11,
        "heading_h5_size_var": 10,
        "heading_h6_size_var": 10,
        "code_font_var": "Courier New",
        "code_size_var": 9,
        "code_line_height_var": 1.2,
        "code_theme_var": "default",
        "margin_top_var": 12.0,
        "margin_right_var": 12.0,
        "margin_bottom_var": 12.0,
        "margin_left_var": 12.0,
        "footer_text_var": "",
        "footer_color_var": "#999999",
        "footer_align_var": "Right",
        "include_notes_var": False,
        "footnote_size_var": 7.5,
        "footnote_text_color_var": "#666666",
        "footnote_marker_color_var": "#333333",
        "table_stripes_var": False,
        "table_odd_color_var": "#ffffff",
        "table_even_color_var": "#f5f5f5",
        "table_pad_y_var": 2,
        "table_pad_x_var": 4,
        "image_scale_var": 65.0,
        "show_horizontal_rules_var": False,
    },
    # ── Warm tones, relaxed feel, like a notebook ────────────────────────
    "Notebook": {
        "body_font_var": "Georgia",
        "heading_font_var": "Segoe UI",
        "body_size_var": 12,
        "line_height_var": 1.7,
        "heading_color_var": "#78350f",
        "heading_h1_color_var": "#78350f",
        "heading_h2_color_var": "#92400e",
        "heading_h3_color_var": "#a16207",
        "heading_h4_color_var": "#b45309",
        "heading_h5_color_var": "",
        "heading_h6_color_var": "",
        "heading_h1_size_var": 28,
        "heading_h2_size_var": 22,
        "heading_h3_size_var": 17,
        "heading_h4_size_var": 15,
        "heading_h5_size_var": 13,
        "heading_h6_size_var": 12,
        "code_font_var": "Courier New",
        "code_size_var": 11,
        "code_line_height_var": 1.5,
        "code_theme_var": "xcode",
        "margin_top_var": 28.0,
        "margin_right_var": 28.0,
        "margin_bottom_var": 28.0,
        "margin_left_var": 28.0,
        "footer_text_var": "",
        "footer_color_var": "#a16207",
        "footer_align_var": "Center",
        "include_notes_var": True,
        "footnote_size_var": 9.0,
        "footnote_text_color_var": "#78350f",
        "footnote_marker_color_var": "#92400e",
        "table_stripes_var": True,
        "table_odd_color_var": "#fffbeb",
        "table_even_color_var": "#fef3c7",
        "table_pad_y_var": 7,
        "table_pad_x_var": 10,
        "image_scale_var": 85.0,
        "show_horizontal_rules_var": True,
    },
    # ── Deep purple accents, creative/design portfolio feel ──────────────
    "Creative": {
        "body_font_var": "Segoe UI",
        "heading_font_var": "Georgia",
        "body_size_var": 11,
        "line_height_var": 1.55,
        "heading_color_var": "#581c87",
        "heading_h1_color_var": "#7c3aed",
        "heading_h2_color_var": "#6d28d9",
        "heading_h3_color_var": "#581c87",
        "heading_h4_color_var": "#6b7280",
        "heading_h5_color_var": "",
        "heading_h6_color_var": "",
        "heading_h1_size_var": 32,
        "heading_h2_size_var": 22,
        "heading_h3_size_var": 16,
        "heading_h4_size_var": 14,
        "heading_h5_size_var": 12,
        "heading_h6_size_var": 11,
        "code_font_var": "Consolas",
        "code_size_var": 10,
        "code_line_height_var": 1.4,
        "code_theme_var": "dracula",
        "margin_top_var": 22.0,
        "margin_right_var": 20.0,
        "margin_bottom_var": 22.0,
        "margin_left_var": 35.0,
        "footer_text_var": "",
        "footer_color_var": "#7c3aed",
        "footer_align_var": "Right",
        "include_notes_var": True,
        "footnote_size_var": 8.5,
        "footnote_text_color_var": "#6b7280",
        "footnote_marker_color_var": "#7c3aed",
        "table_stripes_var": True,
        "table_odd_color_var": "#ffffff",
        "table_even_color_var": "#f5f3ff",
        "table_pad_y_var": 6,
        "table_pad_x_var": 10,
        "image_scale_var": 90.0,
        "show_horizontal_rules_var": True,
    },
    # ── Code-focused with dark code blocks, dev documentation ────────────
    "Developer": {
        "body_font_var": "Segoe UI",
        "heading_font_var": "Consolas",
        "body_size_var": 11,
        "line_height_var": 1.5,
        "heading_color_var": "#0f172a",
        "heading_h1_color_var": "#0ea5e9",
        "heading_h2_color_var": "#0284c7",
        "heading_h3_color_var": "#334155",
        "heading_h4_color_var": "#475569",
        "heading_h5_color_var": "",
        "heading_h6_color_var": "",
        "heading_h1_size_var": 26,
        "heading_h2_size_var": 20,
        "heading_h3_size_var": 16,
        "heading_h4_size_var": 13,
        "heading_h5_size_var": 12,
        "heading_h6_size_var": 11,
        "code_font_var": "Consolas",
        "code_size_var": 11,
        "code_line_height_var": 1.35,
        "code_theme_var": "native",
        "margin_top_var": 20.0,
        "margin_right_var": 20.0,
        "margin_bottom_var": 20.0,
        "margin_left_var": 20.0,
        "footer_text_var": "",
        "footer_color_var": "#475569",
        "footer_align_var": "Right",
        "include_notes_var": True,
        "footnote_size_var": 8.5,
        "footnote_text_color_var": "#64748b",
        "footnote_marker_color_var": "#0ea5e9",
        "table_stripes_var": True,
        "table_odd_color_var": "#ffffff",
        "table_even_color_var": "#f0f9ff",
        "table_pad_y_var": 5,
        "table_pad_x_var": 8,
        "image_scale_var": 80.0,
        "show_horizontal_rules_var": False,
    },
    # ── Elegant, high contrast, luxury document feel ─────────────────────
    "Elegant": {
        "body_font_var": "Georgia",
        "heading_font_var": "Times New Roman",
        "body_size_var": 12,
        "line_height_var": 1.7,
        "heading_color_var": "#18181b",
        "heading_h1_color_var": "#18181b",
        "heading_h2_color_var": "#27272a",
        "heading_h3_color_var": "#3f3f46",
        "heading_h4_color_var": "#52525b",
        "heading_h5_color_var": "",
        "heading_h6_color_var": "",
        "heading_h1_size_var": 30,
        "heading_h2_size_var": 22,
        "heading_h3_size_var": 17,
        "heading_h4_size_var": 14,
        "heading_h5_size_var": 13,
        "heading_h6_size_var": 12,
        "code_font_var": "Courier New",
        "code_size_var": 10,
        "code_line_height_var": 1.4,
        "code_theme_var": "vim",
        "margin_top_var": 35.0,
        "margin_right_var": 30.0,
        "margin_bottom_var": 35.0,
        "margin_left_var": 30.0,
        "footer_text_var": "",
        "footer_color_var": "#a1a1aa",
        "footer_align_var": "Center",
        "include_notes_var": True,
        "footnote_size_var": 9.0,
        "footnote_text_color_var": "#52525b",
        "footnote_marker_color_var": "#18181b",
        "table_stripes_var": False,
        "table_odd_color_var": "#ffffff",
        "table_even_color_var": "#fafafa",
        "table_pad_y_var": 8,
        "table_pad_x_var": 14,
        "image_scale_var": 85.0,
        "show_horizontal_rules_var": True,
    },
}

BUILTIN_PRESET_NAMES: list[str] = sorted(BUILTIN_PRESETS.keys())


def is_builtin_preset(name: str) -> bool:
    """Return True if *name* (without suffix) matches a built-in preset."""
    clean = name.removesuffix(" (built-in)").strip()
    return clean in BUILTIN_PRESETS


def get_builtin_preset(name: str) -> dict[str, object] | None:
    """Return a copy of the built-in preset dict, or None."""
    clean = name.removesuffix(" (built-in)").strip()
    preset = BUILTIN_PRESETS.get(clean)
    if preset is None:
        return None
    return dict(preset)
